//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Desktop.View.CMaterial
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Material", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class Material : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecoUnitarioField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true))
                {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecoUnitario
        {
            get
            {
                return this.PrecoUnitarioField;
            }
            set
            {
                if ((this.PrecoUnitarioField.Equals(value) != true))
                {
                    this.PrecoUnitarioField = value;
                    this.RaisePropertyChanged("PrecoUnitario");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "CMaterial.ICMaterial")]
    public interface ICMaterial
    {
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICMaterial/Inserir", ReplyAction = "http://tempuri.org/ICMaterial/InserirResponse")]
        string Inserir(Contas_a_Pagar___Desktop.View.CMaterial.Material oMaterial);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICMaterial/Inserir", ReplyAction = "http://tempuri.org/ICMaterial/InserirResponse")]
        System.Threading.Tasks.Task<string> InserirAsync(Contas_a_Pagar___Desktop.View.CMaterial.Material oMaterial);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICMaterial/Alterar", ReplyAction = "http://tempuri.org/ICMaterial/AlterarResponse")]
        string Alterar(Contas_a_Pagar___Desktop.View.CMaterial.Material oMaterial);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICMaterial/Alterar", ReplyAction = "http://tempuri.org/ICMaterial/AlterarResponse")]
        System.Threading.Tasks.Task<string> AlterarAsync(Contas_a_Pagar___Desktop.View.CMaterial.Material oMaterial);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICMaterial/Excluir", ReplyAction = "http://tempuri.org/ICMaterial/ExcluirResponse")]
        string Excluir(int ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICMaterial/Excluir", ReplyAction = "http://tempuri.org/ICMaterial/ExcluirResponse")]
        System.Threading.Tasks.Task<string> ExcluirAsync(int ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICMaterial/SelecionarTodos", ReplyAction = "http://tempuri.org/ICMaterial/SelecionarTodosResponse")]
        Contas_a_Pagar___Desktop.View.CMaterial.Material[] SelecionarTodos();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICMaterial/SelecionarTodos", ReplyAction = "http://tempuri.org/ICMaterial/SelecionarTodosResponse")]
        System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CMaterial.Material[]> SelecionarTodosAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICMaterial/SelecionarTodosCriterio", ReplyAction = "http://tempuri.org/ICMaterial/SelecionarTodosCriterioResponse")]
        Contas_a_Pagar___Desktop.View.CMaterial.Material[] SelecionarTodosCriterio(string Criterio, string Escolha);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICMaterial/SelecionarTodosCriterio", ReplyAction = "http://tempuri.org/ICMaterial/SelecionarTodosCriterioResponse")]
        System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CMaterial.Material[]> SelecionarTodosCriterioAsync(string Criterio, string Escolha);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICMaterialChannel : Contas_a_Pagar___Desktop.View.CMaterial.ICMaterial, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CMaterialClient : System.ServiceModel.ClientBase<Contas_a_Pagar___Desktop.View.CMaterial.ICMaterial>, Contas_a_Pagar___Desktop.View.CMaterial.ICMaterial
    {
        public CMaterialClient()
        {
        }

        public CMaterialClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public CMaterialClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CMaterialClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CMaterialClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public string Inserir(Contas_a_Pagar___Desktop.View.CMaterial.Material oMaterial)
        {
            return base.Channel.Inserir(oMaterial);
        }

        public System.Threading.Tasks.Task<string> InserirAsync(Contas_a_Pagar___Desktop.View.CMaterial.Material oMaterial)
        {
            return base.Channel.InserirAsync(oMaterial);
        }

        public string Alterar(Contas_a_Pagar___Desktop.View.CMaterial.Material oMaterial)
        {
            return base.Channel.Alterar(oMaterial);
        }

        public System.Threading.Tasks.Task<string> AlterarAsync(Contas_a_Pagar___Desktop.View.CMaterial.Material oMaterial)
        {
            return base.Channel.AlterarAsync(oMaterial);
        }

        public string Excluir(int ID)
        {
            return base.Channel.Excluir(ID);
        }

        public System.Threading.Tasks.Task<string> ExcluirAsync(int ID)
        {
            return base.Channel.ExcluirAsync(ID);
        }

        public Contas_a_Pagar___Desktop.View.CMaterial.Material[] SelecionarTodos()
        {
            return base.Channel.SelecionarTodos();
        }

        public System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CMaterial.Material[]> SelecionarTodosAsync()
        {
            return base.Channel.SelecionarTodosAsync();
        }

        public Contas_a_Pagar___Desktop.View.CMaterial.Material[] SelecionarTodosCriterio(string Criterio, string Escolha)
        {
            return base.Channel.SelecionarTodosCriterio(Criterio, Escolha);
        }

        public System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CMaterial.Material[]> SelecionarTodosCriterioAsync(string Criterio, string Escolha)
        {
            return base.Channel.SelecionarTodosCriterioAsync(Criterio, Escolha);
        }
    }
}