//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Desktop.View.CAgencia
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Agencia", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class Agencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BancoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GerenteField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Banco
        {
            get
            {
                return this.BancoField;
            }
            set
            {
                if ((this.BancoField.Equals(value) != true))
                {
                    this.BancoField = value;
                    this.RaisePropertyChanged("Banco");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade
        {
            get
            {
                return this.CidadeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CidadeField, value) != true))
                {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EmailField, value) != true))
                {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco
        {
            get
            {
                return this.EnderecoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true))
                {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gerente
        {
            get
            {
                return this.GerenteField;
            }
            set
            {
                if ((object.ReferenceEquals(this.GerenteField, value) != true))
                {
                    this.GerenteField = value;
                    this.RaisePropertyChanged("Gerente");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone
        {
            get
            {
                return this.TelefoneField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true))
                {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PesquisaAgencia", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class PesquisaAgencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgenciaIDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BancoIDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GerenteField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgenciaID
        {
            get
            {
                return this.AgenciaIDField;
            }
            set
            {
                if ((this.AgenciaIDField.Equals(value) != true))
                {
                    this.AgenciaIDField = value;
                    this.RaisePropertyChanged("AgenciaID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BancoID
        {
            get
            {
                return this.BancoIDField;
            }
            set
            {
                if ((this.BancoIDField.Equals(value) != true))
                {
                    this.BancoIDField = value;
                    this.RaisePropertyChanged("BancoID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade
        {
            get
            {
                return this.CidadeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CidadeField, value) != true))
                {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EmailField, value) != true))
                {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco
        {
            get
            {
                return this.EnderecoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true))
                {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gerente
        {
            get
            {
                return this.GerenteField;
            }
            set
            {
                if ((object.ReferenceEquals(this.GerenteField, value) != true))
                {
                    this.GerenteField = value;
                    this.RaisePropertyChanged("Gerente");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomeField, value) != true))
                {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NumeroField, value) != true))
                {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone
        {
            get
            {
                return this.TelefoneField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true))
                {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "CAgencia.ICAgencia")]
    public interface ICAgencia
    {
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAgencia/Inserir", ReplyAction = "http://tempuri.org/ICAgencia/InserirResponse")]
        string Inserir(Contas_a_Pagar___Desktop.View.CAgencia.Agencia oAgencia);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAgencia/Inserir", ReplyAction = "http://tempuri.org/ICAgencia/InserirResponse")]
        System.Threading.Tasks.Task<string> InserirAsync(Contas_a_Pagar___Desktop.View.CAgencia.Agencia oAgencia);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAgencia/Alterar", ReplyAction = "http://tempuri.org/ICAgencia/AlterarResponse")]
        string Alterar(Contas_a_Pagar___Desktop.View.CAgencia.Agencia oAgencia);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAgencia/Alterar", ReplyAction = "http://tempuri.org/ICAgencia/AlterarResponse")]
        System.Threading.Tasks.Task<string> AlterarAsync(Contas_a_Pagar___Desktop.View.CAgencia.Agencia oAgencia);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAgencia/Excluir", ReplyAction = "http://tempuri.org/ICAgencia/ExcluirResponse")]
        string Excluir(int ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAgencia/Excluir", ReplyAction = "http://tempuri.org/ICAgencia/ExcluirResponse")]
        System.Threading.Tasks.Task<string> ExcluirAsync(int ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAgencia/SelecionarTodos", ReplyAction = "http://tempuri.org/ICAgencia/SelecionarTodosResponse")]
        Contas_a_Pagar___Desktop.View.CAgencia.Agencia[] SelecionarTodos();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAgencia/SelecionarTodos", ReplyAction = "http://tempuri.org/ICAgencia/SelecionarTodosResponse")]
        System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CAgencia.Agencia[]> SelecionarTodosAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAgencia/SelecionarTodosCriterio", ReplyAction = "http://tempuri.org/ICAgencia/SelecionarTodosCriterioResponse")]
        Contas_a_Pagar___Desktop.View.CAgencia.Agencia[] SelecionarTodosCriterio(string Criterio, string Escolha);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAgencia/SelecionarTodosCriterio", ReplyAction = "http://tempuri.org/ICAgencia/SelecionarTodosCriterioResponse")]
        System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CAgencia.Agencia[]> SelecionarTodosCriterioAsync(string Criterio, string Escolha);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAgencia/SelecionarTodosView", ReplyAction = "http://tempuri.org/ICAgencia/SelecionarTodosViewResponse")]
        Contas_a_Pagar___Desktop.View.CAgencia.PesquisaAgencia[] SelecionarTodosView();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAgencia/SelecionarTodosView", ReplyAction = "http://tempuri.org/ICAgencia/SelecionarTodosViewResponse")]
        System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CAgencia.PesquisaAgencia[]> SelecionarTodosViewAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAgencia/SelecionarTodosViewCriterio", ReplyAction = "http://tempuri.org/ICAgencia/SelecionarTodosViewCriterioResponse")]
        Contas_a_Pagar___Desktop.View.CAgencia.PesquisaAgencia[] SelecionarTodosViewCriterio(string Criterio, string Escolha);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAgencia/SelecionarTodosViewCriterio", ReplyAction = "http://tempuri.org/ICAgencia/SelecionarTodosViewCriterioResponse")]
        System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CAgencia.PesquisaAgencia[]> SelecionarTodosViewCriterioAsync(string Criterio, string Escolha);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAgencia/AgenciaExiste", ReplyAction = "http://tempuri.org/ICAgencia/AgenciaExisteResponse")]
        bool AgenciaExiste(int ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICAgencia/AgenciaExiste", ReplyAction = "http://tempuri.org/ICAgencia/AgenciaExisteResponse")]
        System.Threading.Tasks.Task<bool> AgenciaExisteAsync(int ID);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICAgenciaChannel : Contas_a_Pagar___Desktop.View.CAgencia.ICAgencia, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CAgenciaClient : System.ServiceModel.ClientBase<Contas_a_Pagar___Desktop.View.CAgencia.ICAgencia>, Contas_a_Pagar___Desktop.View.CAgencia.ICAgencia
    {
        public CAgenciaClient()
        {
        }

        public CAgenciaClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public CAgenciaClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CAgenciaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CAgenciaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public string Inserir(Contas_a_Pagar___Desktop.View.CAgencia.Agencia oAgencia)
        {
            return base.Channel.Inserir(oAgencia);
        }

        public System.Threading.Tasks.Task<string> InserirAsync(Contas_a_Pagar___Desktop.View.CAgencia.Agencia oAgencia)
        {
            return base.Channel.InserirAsync(oAgencia);
        }

        public string Alterar(Contas_a_Pagar___Desktop.View.CAgencia.Agencia oAgencia)
        {
            return base.Channel.Alterar(oAgencia);
        }

        public System.Threading.Tasks.Task<string> AlterarAsync(Contas_a_Pagar___Desktop.View.CAgencia.Agencia oAgencia)
        {
            return base.Channel.AlterarAsync(oAgencia);
        }

        public string Excluir(int ID)
        {
            return base.Channel.Excluir(ID);
        }

        public System.Threading.Tasks.Task<string> ExcluirAsync(int ID)
        {
            return base.Channel.ExcluirAsync(ID);
        }

        public Contas_a_Pagar___Desktop.View.CAgencia.Agencia[] SelecionarTodos()
        {
            return base.Channel.SelecionarTodos();
        }

        public System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CAgencia.Agencia[]> SelecionarTodosAsync()
        {
            return base.Channel.SelecionarTodosAsync();
        }

        public Contas_a_Pagar___Desktop.View.CAgencia.Agencia[] SelecionarTodosCriterio(string Criterio, string Escolha)
        {
            return base.Channel.SelecionarTodosCriterio(Criterio, Escolha);
        }

        public System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CAgencia.Agencia[]> SelecionarTodosCriterioAsync(string Criterio, string Escolha)
        {
            return base.Channel.SelecionarTodosCriterioAsync(Criterio, Escolha);
        }

        public Contas_a_Pagar___Desktop.View.CAgencia.PesquisaAgencia[] SelecionarTodosView()
        {
            return base.Channel.SelecionarTodosView();
        }

        public System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CAgencia.PesquisaAgencia[]> SelecionarTodosViewAsync()
        {
            return base.Channel.SelecionarTodosViewAsync();
        }

        public Contas_a_Pagar___Desktop.View.CAgencia.PesquisaAgencia[] SelecionarTodosViewCriterio(string Criterio, string Escolha)
        {
            return base.Channel.SelecionarTodosViewCriterio(Criterio, Escolha);
        }

        public System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CAgencia.PesquisaAgencia[]> SelecionarTodosViewCriterioAsync(string Criterio, string Escolha)
        {
            return base.Channel.SelecionarTodosViewCriterioAsync(Criterio, Escolha);
        }

        public bool AgenciaExiste(int ID)
        {
            return base.Channel.AgenciaExiste(ID);
        }

        public System.Threading.Tasks.Task<bool> AgenciaExisteAsync(int ID)
        {
            return base.Channel.AgenciaExisteAsync(ID);
        }
    }
}