//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Desktop.View.CLancamento
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Lancamento", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class Lancamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContaCreditoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataLancamentoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.Despesa[] DespesaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.PlanoContas PlanoContasField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContaCredito
        {
            get
            {
                return this.ContaCreditoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContaCreditoField, value) != true))
                {
                    this.ContaCreditoField = value;
                    this.RaisePropertyChanged("ContaCredito");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataLancamento
        {
            get
            {
                return this.DataLancamentoField;
            }
            set
            {
                if ((this.DataLancamentoField.Equals(value) != true))
                {
                    this.DataLancamentoField = value;
                    this.RaisePropertyChanged("DataLancamento");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true))
                {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.Despesa[] Despesa
        {
            get
            {
                return this.DespesaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DespesaField, value) != true))
                {
                    this.DespesaField = value;
                    this.RaisePropertyChanged("Despesa");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                if ((this.NumeroField.Equals(value) != true))
                {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.PlanoContas PlanoContas
        {
            get
            {
                return this.PlanoContasField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PlanoContasField, value) != true))
                {
                    this.PlanoContasField = value;
                    this.RaisePropertyChanged("PlanoContas");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                if ((this.ValorField.Equals(value) != true))
                {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PlanoContas", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class PlanoContas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ConsolidacaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.ContaCorrente ContaCorrenteField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.Lancamento[] LancamentoField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Consolidacao
        {
            get
            {
                return this.ConsolidacaoField;
            }
            set
            {
                if ((this.ConsolidacaoField.Equals(value) != true))
                {
                    this.ConsolidacaoField = value;
                    this.RaisePropertyChanged("Consolidacao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Conta
        {
            get
            {
                return this.ContaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContaField, value) != true))
                {
                    this.ContaField = value;
                    this.RaisePropertyChanged("Conta");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.ContaCorrente ContaCorrente
        {
            get
            {
                return this.ContaCorrenteField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContaCorrenteField, value) != true))
                {
                    this.ContaCorrenteField = value;
                    this.RaisePropertyChanged("ContaCorrente");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true))
                {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.Lancamento[] Lancamento
        {
            get
            {
                return this.LancamentoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LancamentoField, value) != true))
                {
                    this.LancamentoField = value;
                    this.RaisePropertyChanged("Lancamento");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Despesa", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class Despesa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LancamentoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.Lancamento Lancamento1Field;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PagamentoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.Pagamento Pagamento1Field;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorPrevistoField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true))
                {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Lancamento
        {
            get
            {
                return this.LancamentoField;
            }
            set
            {
                if ((this.LancamentoField.Equals(value) != true))
                {
                    this.LancamentoField = value;
                    this.RaisePropertyChanged("Lancamento");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.Lancamento Lancamento1
        {
            get
            {
                return this.Lancamento1Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.Lancamento1Field, value) != true))
                {
                    this.Lancamento1Field = value;
                    this.RaisePropertyChanged("Lancamento1");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                if ((this.NumeroField.Equals(value) != true))
                {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pagamento
        {
            get
            {
                return this.PagamentoField;
            }
            set
            {
                if ((this.PagamentoField.Equals(value) != true))
                {
                    this.PagamentoField = value;
                    this.RaisePropertyChanged("Pagamento");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.Pagamento Pagamento1
        {
            get
            {
                return this.Pagamento1Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.Pagamento1Field, value) != true))
                {
                    this.Pagamento1Field = value;
                    this.RaisePropertyChanged("Pagamento1");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorPrevisto
        {
            get
            {
                return this.ValorPrevistoField;
            }
            set
            {
                if ((this.ValorPrevistoField.Equals(value) != true))
                {
                    this.ValorPrevistoField = value;
                    this.RaisePropertyChanged("ValorPrevisto");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Pagamento", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class Pagamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataEmissaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.Despesa[] DespesaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FornecimentoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.FornecimentoMaterial FornecimentoMaterialField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.FornecimentoMaterial FornecimentoMaterial1Field;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataEmissao
        {
            get
            {
                return this.DataEmissaoField;
            }
            set
            {
                if ((this.DataEmissaoField.Equals(value) != true))
                {
                    this.DataEmissaoField = value;
                    this.RaisePropertyChanged("DataEmissao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.Despesa[] Despesa
        {
            get
            {
                return this.DespesaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DespesaField, value) != true))
                {
                    this.DespesaField = value;
                    this.RaisePropertyChanged("Despesa");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fornecimento
        {
            get
            {
                return this.FornecimentoField;
            }
            set
            {
                if ((this.FornecimentoField.Equals(value) != true))
                {
                    this.FornecimentoField = value;
                    this.RaisePropertyChanged("Fornecimento");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.FornecimentoMaterial FornecimentoMaterial
        {
            get
            {
                return this.FornecimentoMaterialField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FornecimentoMaterialField, value) != true))
                {
                    this.FornecimentoMaterialField = value;
                    this.RaisePropertyChanged("FornecimentoMaterial");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.FornecimentoMaterial FornecimentoMaterial1
        {
            get
            {
                return this.FornecimentoMaterial1Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.FornecimentoMaterial1Field, value) != true))
                {
                    this.FornecimentoMaterial1Field = value;
                    this.RaisePropertyChanged("FornecimentoMaterial1");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                if ((this.ValorField.Equals(value) != true))
                {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "FornecimentoMaterial", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class FornecimentoMaterial : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> CanceladoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FornecedorField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.Fornecedor Fornecedor1Field;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.Material[] MaterialField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.Pagamento PagamentoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.Pagamento Pagamento1Field;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ServicoField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Cancelado
        {
            get
            {
                return this.CanceladoField;
            }
            set
            {
                if ((this.CanceladoField.Equals(value) != true))
                {
                    this.CanceladoField = value;
                    this.RaisePropertyChanged("Cancelado");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                if ((this.DataField.Equals(value) != true))
                {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fornecedor
        {
            get
            {
                return this.FornecedorField;
            }
            set
            {
                if ((this.FornecedorField.Equals(value) != true))
                {
                    this.FornecedorField = value;
                    this.RaisePropertyChanged("Fornecedor");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.Fornecedor Fornecedor1
        {
            get
            {
                return this.Fornecedor1Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.Fornecedor1Field, value) != true))
                {
                    this.Fornecedor1Field = value;
                    this.RaisePropertyChanged("Fornecedor1");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.Material[] Material
        {
            get
            {
                return this.MaterialField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MaterialField, value) != true))
                {
                    this.MaterialField = value;
                    this.RaisePropertyChanged("Material");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.Pagamento Pagamento
        {
            get
            {
                return this.PagamentoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PagamentoField, value) != true))
                {
                    this.PagamentoField = value;
                    this.RaisePropertyChanged("Pagamento");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.Pagamento Pagamento1
        {
            get
            {
                return this.Pagamento1Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.Pagamento1Field, value) != true))
                {
                    this.Pagamento1Field = value;
                    this.RaisePropertyChanged("Pagamento1");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Servico
        {
            get
            {
                return this.ServicoField;
            }
            set
            {
                if ((this.ServicoField.Equals(value) != true))
                {
                    this.ServicoField = value;
                    this.RaisePropertyChanged("Servico");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Fornecedor", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class Fornecedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPJField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.FornecimentoMaterial[] FornecimentoMaterialField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazaoSocialField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNPJ
        {
            get
            {
                return this.CNPJField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CNPJField, value) != true))
                {
                    this.CNPJField = value;
                    this.RaisePropertyChanged("CNPJ");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade
        {
            get
            {
                return this.CidadeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CidadeField, value) != true))
                {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco
        {
            get
            {
                return this.EnderecoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true))
                {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EstadoField, value) != true))
                {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.FornecimentoMaterial[] FornecimentoMaterial
        {
            get
            {
                return this.FornecimentoMaterialField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FornecimentoMaterialField, value) != true))
                {
                    this.FornecimentoMaterialField = value;
                    this.RaisePropertyChanged("FornecimentoMaterial");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazaoSocial
        {
            get
            {
                return this.RazaoSocialField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RazaoSocialField, value) != true))
                {
                    this.RazaoSocialField = value;
                    this.RaisePropertyChanged("RazaoSocial");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Material", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class Material : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.FornecimentoMaterial[] FornecimentoMaterialField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecoUnitarioField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.SolicitacaoMaterial[] SolicitacaoMaterialField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true))
                {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.FornecimentoMaterial[] FornecimentoMaterial
        {
            get
            {
                return this.FornecimentoMaterialField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FornecimentoMaterialField, value) != true))
                {
                    this.FornecimentoMaterialField = value;
                    this.RaisePropertyChanged("FornecimentoMaterial");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecoUnitario
        {
            get
            {
                return this.PrecoUnitarioField;
            }
            set
            {
                if ((this.PrecoUnitarioField.Equals(value) != true))
                {
                    this.PrecoUnitarioField = value;
                    this.RaisePropertyChanged("PrecoUnitario");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.SolicitacaoMaterial[] SolicitacaoMaterial
        {
            get
            {
                return this.SolicitacaoMaterialField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SolicitacaoMaterialField, value) != true))
                {
                    this.SolicitacaoMaterialField = value;
                    this.RaisePropertyChanged("SolicitacaoMaterial");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SolicitacaoMaterial", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class SolicitacaoMaterial : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AprovadoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.Material[] MaterialField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SetorField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.Setor Setor1Field;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aprovado
        {
            get
            {
                return this.AprovadoField;
            }
            set
            {
                if ((this.AprovadoField.Equals(value) != true))
                {
                    this.AprovadoField = value;
                    this.RaisePropertyChanged("Aprovado");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                if ((this.DataField.Equals(value) != true))
                {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.Material[] Material
        {
            get
            {
                return this.MaterialField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MaterialField, value) != true))
                {
                    this.MaterialField = value;
                    this.RaisePropertyChanged("Material");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Setor
        {
            get
            {
                return this.SetorField;
            }
            set
            {
                if ((this.SetorField.Equals(value) != true))
                {
                    this.SetorField = value;
                    this.RaisePropertyChanged("Setor");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.Setor Setor1
        {
            get
            {
                return this.Setor1Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.Setor1Field, value) != true))
                {
                    this.Setor1Field = value;
                    this.RaisePropertyChanged("Setor1");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Setor", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class Setor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.SolicitacaoMaterial[] SolicitacaoMaterialField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true))
                {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.SolicitacaoMaterial[] SolicitacaoMaterial
        {
            get
            {
                return this.SolicitacaoMaterialField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SolicitacaoMaterialField, value) != true))
                {
                    this.SolicitacaoMaterialField = value;
                    this.RaisePropertyChanged("SolicitacaoMaterial");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ContaCorrente", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class ContaCorrente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgenciaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.Agencia Agencia1Field;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LimiteField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.PlanoContas PlanoContasField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Agencia
        {
            get
            {
                return this.AgenciaField;
            }
            set
            {
                if ((this.AgenciaField.Equals(value) != true))
                {
                    this.AgenciaField = value;
                    this.RaisePropertyChanged("Agencia");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.Agencia Agencia1
        {
            get
            {
                return this.Agencia1Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.Agencia1Field, value) != true))
                {
                    this.Agencia1Field = value;
                    this.RaisePropertyChanged("Agencia1");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Conta
        {
            get
            {
                return this.ContaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContaField, value) != true))
                {
                    this.ContaField = value;
                    this.RaisePropertyChanged("Conta");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Limite
        {
            get
            {
                return this.LimiteField;
            }
            set
            {
                if ((this.LimiteField.Equals(value) != true))
                {
                    this.LimiteField = value;
                    this.RaisePropertyChanged("Limite");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.PlanoContas PlanoContas
        {
            get
            {
                return this.PlanoContasField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PlanoContasField, value) != true))
                {
                    this.PlanoContasField = value;
                    this.RaisePropertyChanged("PlanoContas");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Agencia", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class Agencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BancoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.Banco Banco1Field;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.ContaCorrente[] ContaCorrenteField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GerenteField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Banco
        {
            get
            {
                return this.BancoField;
            }
            set
            {
                if ((this.BancoField.Equals(value) != true))
                {
                    this.BancoField = value;
                    this.RaisePropertyChanged("Banco");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.Banco Banco1
        {
            get
            {
                return this.Banco1Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.Banco1Field, value) != true))
                {
                    this.Banco1Field = value;
                    this.RaisePropertyChanged("Banco1");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade
        {
            get
            {
                return this.CidadeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CidadeField, value) != true))
                {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.ContaCorrente[] ContaCorrente
        {
            get
            {
                return this.ContaCorrenteField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContaCorrenteField, value) != true))
                {
                    this.ContaCorrenteField = value;
                    this.RaisePropertyChanged("ContaCorrente");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EmailField, value) != true))
                {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco
        {
            get
            {
                return this.EnderecoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true))
                {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gerente
        {
            get
            {
                return this.GerenteField;
            }
            set
            {
                if ((object.ReferenceEquals(this.GerenteField, value) != true))
                {
                    this.GerenteField = value;
                    this.RaisePropertyChanged("Gerente");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone
        {
            get
            {
                return this.TelefoneField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true))
                {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Banco", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class Banco : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Contas_a_Pagar___Desktop.View.CLancamento.Agencia[] AgenciaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contas_a_Pagar___Desktop.View.CLancamento.Agencia[] Agencia
        {
            get
            {
                return this.AgenciaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AgenciaField, value) != true))
                {
                    this.AgenciaField = value;
                    this.RaisePropertyChanged("Agencia");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomeField, value) != true))
                {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NumeroField, value) != true))
                {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "CLancamento.ICLancamento")]
    public interface ICLancamento
    {
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICLancamento/Inserir", ReplyAction = "http://tempuri.org/ICLancamento/InserirResponse")]
        string Inserir(Contas_a_Pagar___Desktop.View.CLancamento.Lancamento oLancamento);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICLancamento/Inserir", ReplyAction = "http://tempuri.org/ICLancamento/InserirResponse")]
        System.Threading.Tasks.Task<string> InserirAsync(Contas_a_Pagar___Desktop.View.CLancamento.Lancamento oLancamento);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICLancamento/Alterar", ReplyAction = "http://tempuri.org/ICLancamento/AlterarResponse")]
        string Alterar(Contas_a_Pagar___Desktop.View.CLancamento.Lancamento oLancamento);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICLancamento/Alterar", ReplyAction = "http://tempuri.org/ICLancamento/AlterarResponse")]
        System.Threading.Tasks.Task<string> AlterarAsync(Contas_a_Pagar___Desktop.View.CLancamento.Lancamento oLancamento);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICLancamento/Excluir", ReplyAction = "http://tempuri.org/ICLancamento/ExcluirResponse")]
        string Excluir(int ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICLancamento/Excluir", ReplyAction = "http://tempuri.org/ICLancamento/ExcluirResponse")]
        System.Threading.Tasks.Task<string> ExcluirAsync(int ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICLancamento/SelecionarTodos", ReplyAction = "http://tempuri.org/ICLancamento/SelecionarTodosResponse")]
        Contas_a_Pagar___Desktop.View.CLancamento.Lancamento[] SelecionarTodos();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICLancamento/SelecionarTodos", ReplyAction = "http://tempuri.org/ICLancamento/SelecionarTodosResponse")]
        System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CLancamento.Lancamento[]> SelecionarTodosAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICLancamento/SelecionarTodosCriterio", ReplyAction = "http://tempuri.org/ICLancamento/SelecionarTodosCriterioResponse")]
        Contas_a_Pagar___Desktop.View.CLancamento.Lancamento[] SelecionarTodosCriterio(string Criterio, string Escolha);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICLancamento/SelecionarTodosCriterio", ReplyAction = "http://tempuri.org/ICLancamento/SelecionarTodosCriterioResponse")]
        System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CLancamento.Lancamento[]> SelecionarTodosCriterioAsync(string Criterio, string Escolha);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICLancamento/LancamentoExiste", ReplyAction = "http://tempuri.org/ICLancamento/LancamentoExisteResponse")]
        bool LancamentoExiste(int ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICLancamento/LancamentoExiste", ReplyAction = "http://tempuri.org/ICLancamento/LancamentoExisteResponse")]
        System.Threading.Tasks.Task<bool> LancamentoExisteAsync(int ID);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICLancamentoChannel : Contas_a_Pagar___Desktop.View.CLancamento.ICLancamento, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CLancamentoClient : System.ServiceModel.ClientBase<Contas_a_Pagar___Desktop.View.CLancamento.ICLancamento>, Contas_a_Pagar___Desktop.View.CLancamento.ICLancamento
    {
        public CLancamentoClient()
        {
        }

        public CLancamentoClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public CLancamentoClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CLancamentoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CLancamentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public string Inserir(Contas_a_Pagar___Desktop.View.CLancamento.Lancamento oLancamento)
        {
            return base.Channel.Inserir(oLancamento);
        }

        public System.Threading.Tasks.Task<string> InserirAsync(Contas_a_Pagar___Desktop.View.CLancamento.Lancamento oLancamento)
        {
            return base.Channel.InserirAsync(oLancamento);
        }

        public string Alterar(Contas_a_Pagar___Desktop.View.CLancamento.Lancamento oLancamento)
        {
            return base.Channel.Alterar(oLancamento);
        }

        public System.Threading.Tasks.Task<string> AlterarAsync(Contas_a_Pagar___Desktop.View.CLancamento.Lancamento oLancamento)
        {
            return base.Channel.AlterarAsync(oLancamento);
        }

        public string Excluir(int ID)
        {
            return base.Channel.Excluir(ID);
        }

        public System.Threading.Tasks.Task<string> ExcluirAsync(int ID)
        {
            return base.Channel.ExcluirAsync(ID);
        }

        public Contas_a_Pagar___Desktop.View.CLancamento.Lancamento[] SelecionarTodos()
        {
            return base.Channel.SelecionarTodos();
        }

        public System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CLancamento.Lancamento[]> SelecionarTodosAsync()
        {
            return base.Channel.SelecionarTodosAsync();
        }

        public Contas_a_Pagar___Desktop.View.CLancamento.Lancamento[] SelecionarTodosCriterio(string Criterio, string Escolha)
        {
            return base.Channel.SelecionarTodosCriterio(Criterio, Escolha);
        }

        public System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CLancamento.Lancamento[]> SelecionarTodosCriterioAsync(string Criterio, string Escolha)
        {
            return base.Channel.SelecionarTodosCriterioAsync(Criterio, Escolha);
        }

        public bool LancamentoExiste(int ID)
        {
            return base.Channel.LancamentoExiste(ID);
        }

        public System.Threading.Tasks.Task<bool> LancamentoExisteAsync(int ID)
        {
            return base.Channel.LancamentoExisteAsync(ID);
        }
    }
}