//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Desktop.View.CContaCorrente
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ContaCorrente", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class ContaCorrente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgenciaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LimiteField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Agencia
        {
            get
            {
                return this.AgenciaField;
            }
            set
            {
                if ((this.AgenciaField.Equals(value) != true))
                {
                    this.AgenciaField = value;
                    this.RaisePropertyChanged("Agencia");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Conta
        {
            get
            {
                return this.ContaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContaField, value) != true))
                {
                    this.ContaField = value;
                    this.RaisePropertyChanged("Conta");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Limite
        {
            get
            {
                return this.LimiteField;
            }
            set
            {
                if ((this.LimiteField.Equals(value) != true))
                {
                    this.LimiteField = value;
                    this.RaisePropertyChanged("Limite");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PesquisarCC", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class PesquisarCC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgenciaIDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContaField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GerenteField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LimiteField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgenciaID
        {
            get
            {
                return this.AgenciaIDField;
            }
            set
            {
                if ((this.AgenciaIDField.Equals(value) != true))
                {
                    this.AgenciaIDField = value;
                    this.RaisePropertyChanged("AgenciaID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade
        {
            get
            {
                return this.CidadeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CidadeField, value) != true))
                {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Conta
        {
            get
            {
                return this.ContaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContaField, value) != true))
                {
                    this.ContaField = value;
                    this.RaisePropertyChanged("Conta");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EmailField, value) != true))
                {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco
        {
            get
            {
                return this.EnderecoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true))
                {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gerente
        {
            get
            {
                return this.GerenteField;
            }
            set
            {
                if ((object.ReferenceEquals(this.GerenteField, value) != true))
                {
                    this.GerenteField = value;
                    this.RaisePropertyChanged("Gerente");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Limite
        {
            get
            {
                return this.LimiteField;
            }
            set
            {
                if ((this.LimiteField.Equals(value) != true))
                {
                    this.LimiteField = value;
                    this.RaisePropertyChanged("Limite");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomeField, value) != true))
                {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NumeroField, value) != true))
                {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone
        {
            get
            {
                return this.TelefoneField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true))
                {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "CContaCorrente.ICContaCorrente")]
    public interface ICContaCorrente
    {
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICContaCorrente/Inserir", ReplyAction = "http://tempuri.org/ICContaCorrente/InserirResponse")]
        string Inserir(Contas_a_Pagar___Desktop.View.CContaCorrente.ContaCorrente oContaCorrente);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICContaCorrente/Inserir", ReplyAction = "http://tempuri.org/ICContaCorrente/InserirResponse")]
        System.Threading.Tasks.Task<string> InserirAsync(Contas_a_Pagar___Desktop.View.CContaCorrente.ContaCorrente oContaCorrente);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICContaCorrente/Alterar", ReplyAction = "http://tempuri.org/ICContaCorrente/AlterarResponse")]
        string Alterar(Contas_a_Pagar___Desktop.View.CContaCorrente.ContaCorrente oContaCorrente);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICContaCorrente/Alterar", ReplyAction = "http://tempuri.org/ICContaCorrente/AlterarResponse")]
        System.Threading.Tasks.Task<string> AlterarAsync(Contas_a_Pagar___Desktop.View.CContaCorrente.ContaCorrente oContaCorrente);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICContaCorrente/Excluir", ReplyAction = "http://tempuri.org/ICContaCorrente/ExcluirResponse")]
        string Excluir(string Conta);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICContaCorrente/Excluir", ReplyAction = "http://tempuri.org/ICContaCorrente/ExcluirResponse")]
        System.Threading.Tasks.Task<string> ExcluirAsync(string Conta);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICContaCorrente/SelecionarTodos", ReplyAction = "http://tempuri.org/ICContaCorrente/SelecionarTodosResponse")]
        Contas_a_Pagar___Desktop.View.CContaCorrente.ContaCorrente[] SelecionarTodos();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICContaCorrente/SelecionarTodos", ReplyAction = "http://tempuri.org/ICContaCorrente/SelecionarTodosResponse")]
        System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CContaCorrente.ContaCorrente[]> SelecionarTodosAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICContaCorrente/SelecionarTodosCriterio", ReplyAction = "http://tempuri.org/ICContaCorrente/SelecionarTodosCriterioResponse")]
        Contas_a_Pagar___Desktop.View.CContaCorrente.ContaCorrente[] SelecionarTodosCriterio(string Criterio, string Escolha);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICContaCorrente/SelecionarTodosCriterio", ReplyAction = "http://tempuri.org/ICContaCorrente/SelecionarTodosCriterioResponse")]
        System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CContaCorrente.ContaCorrente[]> SelecionarTodosCriterioAsync(string Criterio, string Escolha);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICContaCorrente/SelecionarTodosView", ReplyAction = "http://tempuri.org/ICContaCorrente/SelecionarTodosViewResponse")]
        Contas_a_Pagar___Desktop.View.CContaCorrente.PesquisarCC[] SelecionarTodosView();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICContaCorrente/SelecionarTodosView", ReplyAction = "http://tempuri.org/ICContaCorrente/SelecionarTodosViewResponse")]
        System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CContaCorrente.PesquisarCC[]> SelecionarTodosViewAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICContaCorrente/SelecionarTodosViewCriterio", ReplyAction = "http://tempuri.org/ICContaCorrente/SelecionarTodosViewCriterioResponse")]
        Contas_a_Pagar___Desktop.View.CContaCorrente.PesquisarCC[] SelecionarTodosViewCriterio(string Criterio, string Escolha);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICContaCorrente/SelecionarTodosViewCriterio", ReplyAction = "http://tempuri.org/ICContaCorrente/SelecionarTodosViewCriterioResponse")]
        System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CContaCorrente.PesquisarCC[]> SelecionarTodosViewCriterioAsync(string Criterio, string Escolha);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICContaCorrente/ContaCorrenteExiste", ReplyAction = "http://tempuri.org/ICContaCorrente/ContaCorrenteExisteResponse")]
        bool ContaCorrenteExiste(string Conta);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICContaCorrente/ContaCorrenteExiste", ReplyAction = "http://tempuri.org/ICContaCorrente/ContaCorrenteExisteResponse")]
        System.Threading.Tasks.Task<bool> ContaCorrenteExisteAsync(string Conta);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICContaCorrenteChannel : Contas_a_Pagar___Desktop.View.CContaCorrente.ICContaCorrente, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CContaCorrenteClient : System.ServiceModel.ClientBase<Contas_a_Pagar___Desktop.View.CContaCorrente.ICContaCorrente>, Contas_a_Pagar___Desktop.View.CContaCorrente.ICContaCorrente
    {
        public CContaCorrenteClient()
        {
        }

        public CContaCorrenteClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public CContaCorrenteClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CContaCorrenteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CContaCorrenteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public string Inserir(Contas_a_Pagar___Desktop.View.CContaCorrente.ContaCorrente oContaCorrente)
        {
            return base.Channel.Inserir(oContaCorrente);
        }

        public System.Threading.Tasks.Task<string> InserirAsync(Contas_a_Pagar___Desktop.View.CContaCorrente.ContaCorrente oContaCorrente)
        {
            return base.Channel.InserirAsync(oContaCorrente);
        }

        public string Alterar(Contas_a_Pagar___Desktop.View.CContaCorrente.ContaCorrente oContaCorrente)
        {
            return base.Channel.Alterar(oContaCorrente);
        }

        public System.Threading.Tasks.Task<string> AlterarAsync(Contas_a_Pagar___Desktop.View.CContaCorrente.ContaCorrente oContaCorrente)
        {
            return base.Channel.AlterarAsync(oContaCorrente);
        }

        public string Excluir(string Conta)
        {
            return base.Channel.Excluir(Conta);
        }

        public System.Threading.Tasks.Task<string> ExcluirAsync(string Conta)
        {
            return base.Channel.ExcluirAsync(Conta);
        }

        public Contas_a_Pagar___Desktop.View.CContaCorrente.ContaCorrente[] SelecionarTodos()
        {
            return base.Channel.SelecionarTodos();
        }

        public System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CContaCorrente.ContaCorrente[]> SelecionarTodosAsync()
        {
            return base.Channel.SelecionarTodosAsync();
        }

        public Contas_a_Pagar___Desktop.View.CContaCorrente.ContaCorrente[] SelecionarTodosCriterio(string Criterio, string Escolha)
        {
            return base.Channel.SelecionarTodosCriterio(Criterio, Escolha);
        }

        public System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CContaCorrente.ContaCorrente[]> SelecionarTodosCriterioAsync(string Criterio, string Escolha)
        {
            return base.Channel.SelecionarTodosCriterioAsync(Criterio, Escolha);
        }

        public Contas_a_Pagar___Desktop.View.CContaCorrente.PesquisarCC[] SelecionarTodosView()
        {
            return base.Channel.SelecionarTodosView();
        }

        public System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CContaCorrente.PesquisarCC[]> SelecionarTodosViewAsync()
        {
            return base.Channel.SelecionarTodosViewAsync();
        }

        public Contas_a_Pagar___Desktop.View.CContaCorrente.PesquisarCC[] SelecionarTodosViewCriterio(string Criterio, string Escolha)
        {
            return base.Channel.SelecionarTodosViewCriterio(Criterio, Escolha);
        }

        public System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CContaCorrente.PesquisarCC[]> SelecionarTodosViewCriterioAsync(string Criterio, string Escolha)
        {
            return base.Channel.SelecionarTodosViewCriterioAsync(Criterio, Escolha);
        }

        public bool ContaCorrenteExiste(string Conta)
        {
            return base.Channel.ContaCorrenteExiste(Conta);
        }

        public System.Threading.Tasks.Task<bool> ContaCorrenteExisteAsync(string Conta)
        {
            return base.Channel.ContaCorrenteExisteAsync(Conta);
        }
    }
}