//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class AspNetUserClaims
    {
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public string UserId { get; set; }
    	[DataMember]
        public string ClaimType { get; set; }
    	[DataMember]
        public string ClaimValue { get; set; }
    
    	[DataMember]
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
