//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class Auditoria
    {
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public string Evento { get; set; }
    	[DataMember]
        public string Usuario { get; set; }
    	[DataMember]
        public System.DateTime DataHora { get; set; }
    	[DataMember]
        public string Descricao { get; set; }
    
    	[DataMember]
        public virtual Evento Evento1 { get; set; }
    }
}
