//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class Despesa
    {
    	[DataMember]
        public int Numero { get; set; }
    	[DataMember]
        public int Lancamento { get; set; }
    	[DataMember]
        public decimal ValorPrevisto { get; set; }
    	[DataMember]
        public string Descricao { get; set; }
    	[DataMember]
        public int Pagamento { get; set; }
    
    	[DataMember]
        public virtual Lancamento Lancamento1 { get; set; }
    	[DataMember]
        public virtual Pagamento Pagamento1 { get; set; }
    }
}
