//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class FornecimentoMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FornecimentoMaterial()
        {
            this.Material = new HashSet<Material>();
        }
    
    	[DataMember]
        public int Fornecedor { get; set; }
    	[DataMember]
        public int Servico { get; set; }
    	[DataMember]
        public System.DateTime Data { get; set; }
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public Nullable<bool> Cancelado { get; set; }
    
    	[DataMember]
        public virtual Fornecedor Fornecedor1 { get; set; }
    	[DataMember]
        public virtual Pagamento Pagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual ICollection<Material> Material { get; set; }
    	[DataMember]
        public virtual Pagamento Pagamento1 { get; set; }
    }
}
