//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class PesquisaAgencia
    {
    	[DataMember]
        public int AgenciaID { get; set; }
    	[DataMember]
        public string Endereco { get; set; }
    	[DataMember]
        public string Cidade { get; set; }
    	[DataMember]
        public string Gerente { get; set; }
    	[DataMember]
        public string Telefone { get; set; }
    	[DataMember]
        public string Email { get; set; }
    	[DataMember]
        public int BancoID { get; set; }
    	[DataMember]
        public string Nome { get; set; }
    	[DataMember]
        public string Numero { get; set; }
    }
}
