//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Desktop.View.CSetor
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Setor", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class Setor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true))
                {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "CSetor.ICSetor")]
    public interface ICSetor
    {
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICSetor/Inserir", ReplyAction = "http://tempuri.org/ICSetor/InserirResponse")]
        string Inserir(Contas_a_Pagar___Desktop.View.CSetor.Setor oSetor);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICSetor/Inserir", ReplyAction = "http://tempuri.org/ICSetor/InserirResponse")]
        System.Threading.Tasks.Task<string> InserirAsync(Contas_a_Pagar___Desktop.View.CSetor.Setor oSetor);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICSetor/Alterar", ReplyAction = "http://tempuri.org/ICSetor/AlterarResponse")]
        string Alterar(Contas_a_Pagar___Desktop.View.CSetor.Setor oSetor);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICSetor/Alterar", ReplyAction = "http://tempuri.org/ICSetor/AlterarResponse")]
        System.Threading.Tasks.Task<string> AlterarAsync(Contas_a_Pagar___Desktop.View.CSetor.Setor oSetor);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICSetor/Excluir", ReplyAction = "http://tempuri.org/ICSetor/ExcluirResponse")]
        string Excluir(int ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICSetor/Excluir", ReplyAction = "http://tempuri.org/ICSetor/ExcluirResponse")]
        System.Threading.Tasks.Task<string> ExcluirAsync(int ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICSetor/SelecionarTodos", ReplyAction = "http://tempuri.org/ICSetor/SelecionarTodosResponse")]
        Contas_a_Pagar___Desktop.View.CSetor.Setor[] SelecionarTodos();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICSetor/SelecionarTodos", ReplyAction = "http://tempuri.org/ICSetor/SelecionarTodosResponse")]
        System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CSetor.Setor[]> SelecionarTodosAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICSetor/SelecionarTodosCriterio", ReplyAction = "http://tempuri.org/ICSetor/SelecionarTodosCriterioResponse")]
        Contas_a_Pagar___Desktop.View.CSetor.Setor[] SelecionarTodosCriterio(string Criterio, string Escolha);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICSetor/SelecionarTodosCriterio", ReplyAction = "http://tempuri.org/ICSetor/SelecionarTodosCriterioResponse")]
        System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CSetor.Setor[]> SelecionarTodosCriterioAsync(string Criterio, string Escolha);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICSetorChannel : Contas_a_Pagar___Desktop.View.CSetor.ICSetor, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CSetorClient : System.ServiceModel.ClientBase<Contas_a_Pagar___Desktop.View.CSetor.ICSetor>, Contas_a_Pagar___Desktop.View.CSetor.ICSetor
    {
        public CSetorClient()
        {
        }

        public CSetorClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public CSetorClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CSetorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CSetorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public string Inserir(Contas_a_Pagar___Desktop.View.CSetor.Setor oSetor)
        {
            return base.Channel.Inserir(oSetor);
        }

        public System.Threading.Tasks.Task<string> InserirAsync(Contas_a_Pagar___Desktop.View.CSetor.Setor oSetor)
        {
            return base.Channel.InserirAsync(oSetor);
        }

        public string Alterar(Contas_a_Pagar___Desktop.View.CSetor.Setor oSetor)
        {
            return base.Channel.Alterar(oSetor);
        }

        public System.Threading.Tasks.Task<string> AlterarAsync(Contas_a_Pagar___Desktop.View.CSetor.Setor oSetor)
        {
            return base.Channel.AlterarAsync(oSetor);
        }

        public string Excluir(int ID)
        {
            return base.Channel.Excluir(ID);
        }

        public System.Threading.Tasks.Task<string> ExcluirAsync(int ID)
        {
            return base.Channel.ExcluirAsync(ID);
        }

        public Contas_a_Pagar___Desktop.View.CSetor.Setor[] SelecionarTodos()
        {
            return base.Channel.SelecionarTodos();
        }

        public System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CSetor.Setor[]> SelecionarTodosAsync()
        {
            return base.Channel.SelecionarTodosAsync();
        }

        public Contas_a_Pagar___Desktop.View.CSetor.Setor[] SelecionarTodosCriterio(string Criterio, string Escolha)
        {
            return base.Channel.SelecionarTodosCriterio(Criterio, Escolha);
        }

        public System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CSetor.Setor[]> SelecionarTodosCriterioAsync(string Criterio, string Escolha)
        {
            return base.Channel.SelecionarTodosCriterioAsync(Criterio, Escolha);
        }
    }
}