//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contas_a_Pagar___Desktop.View.CBanco
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Banco", Namespace = "http://schemas.datacontract.org/2004/07/Contas_a_Pagar___Desktop.Model", IsReference = true)]
    [System.SerializableAttribute()]
    public partial class Banco : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomeField, value) != true))
                {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NumeroField, value) != true))
                {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "CBanco.ICBanco")]
    public interface ICBanco
    {
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBanco/Inserir", ReplyAction = "http://tempuri.org/ICBanco/InserirResponse")]
        string Inserir(Contas_a_Pagar___Desktop.View.CBanco.Banco oBanco);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBanco/Inserir", ReplyAction = "http://tempuri.org/ICBanco/InserirResponse")]
        System.Threading.Tasks.Task<string> InserirAsync(Contas_a_Pagar___Desktop.View.CBanco.Banco oBanco);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBanco/Alterar", ReplyAction = "http://tempuri.org/ICBanco/AlterarResponse")]
        string Alterar(Contas_a_Pagar___Desktop.View.CBanco.Banco oBanco);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBanco/Alterar", ReplyAction = "http://tempuri.org/ICBanco/AlterarResponse")]
        System.Threading.Tasks.Task<string> AlterarAsync(Contas_a_Pagar___Desktop.View.CBanco.Banco oBanco);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBanco/Excluir", ReplyAction = "http://tempuri.org/ICBanco/ExcluirResponse")]
        string Excluir(int ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBanco/Excluir", ReplyAction = "http://tempuri.org/ICBanco/ExcluirResponse")]
        System.Threading.Tasks.Task<string> ExcluirAsync(int ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBanco/SelecionarTodos", ReplyAction = "http://tempuri.org/ICBanco/SelecionarTodosResponse")]
        Contas_a_Pagar___Desktop.View.CBanco.Banco[] SelecionarTodos();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBanco/SelecionarTodos", ReplyAction = "http://tempuri.org/ICBanco/SelecionarTodosResponse")]
        System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CBanco.Banco[]> SelecionarTodosAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBanco/SelecionarTodosCriterio", ReplyAction = "http://tempuri.org/ICBanco/SelecionarTodosCriterioResponse")]
        Contas_a_Pagar___Desktop.View.CBanco.Banco[] SelecionarTodosCriterio(string Criterio, string Escolha);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBanco/SelecionarTodosCriterio", ReplyAction = "http://tempuri.org/ICBanco/SelecionarTodosCriterioResponse")]
        System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CBanco.Banco[]> SelecionarTodosCriterioAsync(string Criterio, string Escolha);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBanco/BancoExiste", ReplyAction = "http://tempuri.org/ICBanco/BancoExisteResponse")]
        bool BancoExiste(int ID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICBanco/BancoExiste", ReplyAction = "http://tempuri.org/ICBanco/BancoExisteResponse")]
        System.Threading.Tasks.Task<bool> BancoExisteAsync(int ID);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICBancoChannel : Contas_a_Pagar___Desktop.View.CBanco.ICBanco, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CBancoClient : System.ServiceModel.ClientBase<Contas_a_Pagar___Desktop.View.CBanco.ICBanco>, Contas_a_Pagar___Desktop.View.CBanco.ICBanco
    {
        public CBancoClient()
        {
        }

        public CBancoClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public CBancoClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CBancoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CBancoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public string Inserir(Contas_a_Pagar___Desktop.View.CBanco.Banco oBanco)
        {
            return base.Channel.Inserir(oBanco);
        }

        public System.Threading.Tasks.Task<string> InserirAsync(Contas_a_Pagar___Desktop.View.CBanco.Banco oBanco)
        {
            return base.Channel.InserirAsync(oBanco);
        }

        public string Alterar(Contas_a_Pagar___Desktop.View.CBanco.Banco oBanco)
        {
            return base.Channel.Alterar(oBanco);
        }

        public System.Threading.Tasks.Task<string> AlterarAsync(Contas_a_Pagar___Desktop.View.CBanco.Banco oBanco)
        {
            return base.Channel.AlterarAsync(oBanco);
        }

        public string Excluir(int ID)
        {
            return base.Channel.Excluir(ID);
        }

        public System.Threading.Tasks.Task<string> ExcluirAsync(int ID)
        {
            return base.Channel.ExcluirAsync(ID);
        }

        public Contas_a_Pagar___Desktop.View.CBanco.Banco[] SelecionarTodos()
        {
            return base.Channel.SelecionarTodos();
        }

        public System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CBanco.Banco[]> SelecionarTodosAsync()
        {
            return base.Channel.SelecionarTodosAsync();
        }

        public Contas_a_Pagar___Desktop.View.CBanco.Banco[] SelecionarTodosCriterio(string Criterio, string Escolha)
        {
            return base.Channel.SelecionarTodosCriterio(Criterio, Escolha);
        }

        public System.Threading.Tasks.Task<Contas_a_Pagar___Desktop.View.CBanco.Banco[]> SelecionarTodosCriterioAsync(string Criterio, string Escolha)
        {
            return base.Channel.SelecionarTodosCriterioAsync(Criterio, Escolha);
        }

        public bool BancoExiste(int ID)
        {
            return base.Channel.BancoExiste(ID);
        }

        public System.Threading.Tasks.Task<bool> BancoExisteAsync(int ID)
        {
            return base.Channel.BancoExisteAsync(ID);
        }
    }
}